import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  Search, Heart, ShoppingBag, Menu, X, Sparkles, ChevronRight, Star,
  SlidersHorizontal, GitCompare, Trash2, Plus, Minus, Check, ArrowLeft,
  BookOpen, ShieldCheck, Bell, Award, Sun, Moon, MessageCircle, Send,
  BarChart3, Package, Users, TrendingUp, Pencil, RotateCcw
} from "lucide-react";
import "./styles.css";

const img = (seed) => `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=900&q=80`;

const PRODUCTS = [
  ["p1","Luma Lab","Cloud Barrier Cream","Skincare","Moisturizer",699,4.8,324,img("1556228578-8c89e7adf52b"),["Normal","Dry","Combination","Sensitive"],["Dryness","Redness","Fine Lines"],["Ceramides","Hyaluronic Acid","Niacinamide"],"Deeply cushions skin with a soft, lightweight barrier-supporting texture.",["Hydrates","Supports skin barrier","Comforts dry-feeling skin"],["hydrating","barrier"],"In stock"],
  ["p2","Glow Theory","Clear Balance Serum","Skincare","Serum",899,4.7,512,img("1620916566398-39f0f8a9b7e4"),["Oily","Combination"],["Acne","Oiliness","Pores"],["Niacinamide","Salicylic Acid","Zinc"],"A demo clarifying serum designed for a balanced-looking complexion.",["Helps reduce the look of excess oil","Refines appearance of pores","Brightens"],["clarifying","niacinamide"],"In stock"],
  ["p3","Aster & Bloom","Dew Drop HA Serum","Skincare","Serum",749,4.9,680,img("1611930022073-b7a4ba5fcccd"),["Dry","Normal","Combination","Sensitive"],["Dryness","Dullness","Fine Lines"],["Hyaluronic Acid","Panthenol","Glycerin"],"A fresh hydration serum for a plump, dewy-looking finish.",["Hydrates","Smooths appearance","Layers easily"],["hydration","dewy"],"In stock"],
  ["p4","Velora Skin","C+ Brightening Drops","Skincare","Serum",1099,4.6,281,img("1612817288484-6f916006741a1"),["Normal","Dry","Combination","Oily"],["Dark Spots","Pigmentation","Dullness","Uneven Skin Tone"],["Vitamin C","Ferulic Acid","Vitamin E"],"A demo antioxidant serum created for a brighter-looking complexion.",["Brightens appearance","Supports glow","Antioxidant care"],["brightening","vitamin-c"],"In stock"],
  ["p5","Nuvé","Soft Shield SPF 50","Skincare","Sunscreen",899,4.8,903,img("1556229010-2c1c1c9f6f5c"),["Normal","Dry","Oily","Combination","Sensitive"],["Pigmentation","Dark Spots","Uneven Skin Tone"],["Ceramides","Glycerin","Vitamin E"],"Lightweight daily sunscreen demo with a comfortable finish.",["Daily UV protection","Moisturizing feel","No heavy finish"],["spf","daily"],"In stock"],
  ["p6","Mira Botanics","Gentle Milk Cleanser","Skincare","Cleanser",549,4.7,407,img("1556228852-80b6e4c9b8a7"),["Dry","Normal","Sensitive","Combination"],["Dryness","Redness"],["Ceramides","Oat Extract","Glycerin"],"A creamy demo cleanser for a comfortable cleansing step.",["Cleanses gently","Comforting feel","Non-stripping demo formula"],["gentle","cleanser"],"In stock"],
  ["p7","Dermaluxe Demo","BHA Pore Reset","Skincare","Treatment",799,4.5,239,img("1612810436541-3b2f0b1c9c4e"),["Oily","Combination"],["Acne","Pores","Oiliness"],["Salicylic Acid","BHA","Niacinamide"],"A demo BHA treatment for users interested in pore-focused routines.",["Pore-focused care","Helps manage oily appearance","Smooth-looking texture"],["bha","pores"],"In stock"],
  ["p8","Petal & Pure","Calm Redness Gel","Skincare","Gel",649,4.6,198,img("1611930022073-b7a4ba5fcccd"),["Sensitive","Dry","Normal"],["Redness","Dryness"],["Aloe","Panthenol","Centella"],"A cooling demo gel for a calm-looking, hydrated finish.",["Cooling feel","Hydrates","Comfort-focused"],["calming","gel"],"In stock"],
  ["p9","Luma Lab","Ceramide Clean Foam","Skincare","Cleanser",599,4.8,344,img("1556228578-8c89e7adf52b"),["Oily","Combination","Normal","Sensitive"],["Oiliness","Pores","Dryness"],["Ceramides","Amino Acids","Glycerin"],"A balanced foam cleanser demo that keeps the routine feeling fresh.",["Cleanses","Supports comfortable feel","Easy rinse"],["cleanser","ceramides"],"In stock"],
  ["p10","Glow Theory","Azelaic Tone Cream","Skincare","Treatment",949,4.6,226,img("1612817288484-6f916006741a1"),["Oily","Combination","Sensitive"],["Pigmentation","Redness","Uneven Skin Tone","Acne"],["Azelaic Acid","Niacinamide","Panthenol"],"A demo tone-care cream for a more even-looking complexion.",["Brightens appearance","Calms-looking skin","Refines tone"],["azelaic","tone"],"In stock"],
  ["p11","Aster & Bloom","Overnight Dew Mask","Skincare","Mask",899,4.9,185,img("1611930022073-b7a4ba5fcccd"),["Dry","Normal","Combination"],["Dryness","Dullness","Fine Lines"],["Hyaluronic Acid","Ceramides","Squalane"],"A rich overnight demo mask for a rested, dewy appearance.",["Overnight hydration","Softens feel","Glow boost"],["mask","hydration"],"In stock"],
  ["p12","Velora Skin","Retinol Renewal Demo","Skincare","Treatment",1299,4.5,164,img("1612817288484-6f916006741a1"),["Normal","Dry","Combination","Oily"],["Fine Lines","Uneven Skin Tone","Dullness"],["Retinol","Ceramides","Squalane"],"A demo retinol product for users exploring a refined-looking routine.",["Smooth-looking texture","Supports even appearance","Night routine"],["retinol","anti-aging"],"In stock"],
  ["p13","Nuvé","Velvet Lip Balm","Makeup",399,4.8,712,img("1586495777744-4413f21062fa"),["Normal","Dry","Sensitive"],["Dryness"],["Shea Butter","Vitamin E","Squalane"],"A cushiony demo lip balm with a soft glossy finish.",["Softens lips","Comforting shine","Daily use"],["lip","hydration"],"In stock"],
  ["p14","Mira Botanics","Cloud Hair Mask","Haircare","Hair Mask",799,4.7,311,img("1522337360788-8b13dee7a6f5"),["Normal","Dry"],["Dryness"],["Amino Acids","Argan Oil","Panthenol"],"A demo nourishing mask for smoother-feeling hair.",["Softens hair","Adds slip","Nourishing feel"],["hair","mask"],"In stock"],
  ["p15","Petal & Pure","Silk Scalp Shampoo","Haircare","Shampoo",649,4.6,402,img("1527799820374-dcf8d8d8f3b6"),["Normal","Oily"],["Oiliness"],["Niacinamide","Amino Acids","Green Tea"],"A fresh demo shampoo for a clean, lightweight scalp feel.",["Cleanses","Fresh feel","Lightweight finish"],["hair","scalp"],"In stock"],
  ["p16","Luma Lab","Smooth Ends Hair Oil","Haircare","Hair Oil",599,4.7,521,img("1526047932273-8b7d5a3d1e6a"),["Normal","Dry"],["Dryness"],["Argan Oil","Vitamin E","Squalane"],"A lightweight demo oil for polished-looking ends.",["Adds shine","Softens feel","Smooths appearance"],["hair","shine"],"In stock"],
  ["p17","Glow Theory","Body Cloud Lotion","Body Care","Body Lotion",549,4.8,440,img("1608248543805-6c8a3a9e4f6d"),["Normal","Dry","Sensitive"],["Dryness","Redness"],["Ceramides","Hyaluronic Acid","Glycerin"],"A plush demo body lotion with a creamy finish.",["Hydrates body skin","Soft feel","Comforting texture"],["body","hydration"],"In stock"],
  ["p18","Aster & Bloom","Citrus Body Wash","Body Care","Body Wash",449,4.6,390,img("1608248543805-6c8a3a9e4f6d"),["Normal","Oily","Combination"],["Oiliness","Dullness"],["AHA","Glycerin","Vitamin C"],"A bright, fresh-feeling demo body wash.",["Cleanses","Fresh feel","Smooth-looking skin"],["body","fresh"],"In stock"],
  ["p19","Velora Skin","Glow Body Polish","Body Care","Body Scrub",699,4.5,275,img("1608248543805-6c8a3a9e4f6d"),["Normal","Dry","Combination"],["Dullness","Uneven Skin Tone"],["AHA","Vitamin C","Glycerin"],"A demo exfoliating body polish for smoother-looking skin.",["Polishes","Brightens appearance","Smooth feel"],["body","aha"],"In stock"],
  ["p20","Nuvé","Daily Tint SPF 40","Makeup","Tinted SPF",999,4.7,622,img("1522337360788-8b13dee7a6f5"),["Normal","Dry","Oily","Combination"],["Uneven Skin Tone","Dullness","Pigmentation"],["Vitamin E","Niacinamide","Mineral Filters"],"A demo complexion tint with daily SPF positioning.",["Evens appearance","Daily protection","Natural finish"],["makeup","spf"],"In stock"],
  ["p21","Mira Botanics","Cloud Blush Cream","Makeup","Blush",599,4.8,514,img("1596462502278-27bfdc403348"),["Normal","Dry","Oily","Combination","Sensitive"],["Dullness"],["Squalane","Vitamin E"],"A creamy demo blush for a soft, fresh flush.",["Buildable color","Soft finish","Easy blend"],["makeup","blush"],"In stock"],
  ["p22","Petal & Pure","Lash Lift Mascara","Makeup","Mascara",699,4.6,481,img("1516975080664-ed2fc6a32937"),["Normal","Dry","Oily","Combination","Sensitive"],[],["Vitamin E","Panthenol"],"A demo mascara designed for defined-looking lashes.",["Defines","Buildable look","Comfortable wear"],["makeup","eyes"],"In stock"],
  ["p23","Luma Lab","Peptide Eye Cream","Skincare","Eye Cream",1099,4.7,214,img("1612817288484-6f916006741a1"),["Normal","Dry","Combination"],["Fine Lines","Dryness","Dullness"],["Peptides","Ceramides","Hyaluronic Acid"],"A demo eye cream for a hydrated, refreshed-looking eye area.",["Hydrates","Smooths appearance","Brightens-looking"],["eyes","peptides"],"In stock"],
  ["p24","Glow Theory","Pore Blur Moisturizer","Skincare","Moisturizer",749,4.6,355,img("1556228578-8c89e7adf52b"),["Oily","Combination"],["Pores","Oiliness","Acne"],["Niacinamide","Hyaluronic Acid","Zinc"],"A lightweight demo moisturizer for a soft, balanced finish.",["Light hydration","Refines appearance","Non-heavy feel"],["pores","oil-control"],"In stock"],
  ["p25","Aster & Bloom","Vitamin C Clean Gel","Skincare","Cleanser",649,4.7,301,img("1556228852-80b6e4c9b8a7"),["Oily","Combination","Normal"],["Dullness","Uneven Skin Tone"],["Vitamin C","Glycerin","AHA"],"A fresh demo gel cleanser for a brighter-looking routine.",["Cleanses","Fresh feel","Glow-focused"],["cleanser","brightening"],"In stock"],
  ["p26","Velora Skin","Barrier Rescue Serum","Skincare","Serum",1199,4.9,453,img("1611930022073-b7a4ba5fcccd"),["Dry","Sensitive","Normal"],["Dryness","Redness","Fine Lines"],["Ceramides","Panthenol","Hyaluronic Acid"],"A concentrated demo serum for barrier-focused routines.",["Hydrates","Comforting feel","Supports barrier"],["barrier","serum"],"In stock"],
  ["p27","Nuvé","AHA Glow Essence","Skincare","Essence",899,4.5,182,img("1612817288484-6f916006741a1"),["Normal","Oily","Combination"],["Dullness","Uneven Skin Tone","Pores"],["AHA","Glycerin","Niacinamide"],"A demo essence for a smoother, glow-focused routine.",["Smooths appearance","Hydrates","Glow boost"],["aha","glow"],"In stock"],
  ["p28","Mira Botanics","Squalane Soft Cream","Skincare","Moisturizer",849,4.8,378,img("1556228578-8c89e7adf52b"),["Dry","Normal","Sensitive"],["Dryness","Fine Lines","Redness"],["Squalane","Ceramides","Vitamin E"],"A rich demo cream with a silky finish.",["Softens","Locks in moisture","Comforting feel"],["squalane","cream"],"In stock"],
  ["p29","Petal & Pure","Tea Tree Spot Gel","Skincare","Spot Gel",499,4.4,207,img("1612810436541-3b2f0b1c9c4e"),["Oily","Combination"],["Acne","Oiliness"],["Tea Tree","Salicylic Acid","Niacinamide"],"A demo spot-care gel for targeted cosmetic routines.",["Targeted care","Fresh feel","Oil-focused"],["acne","spot"],"In stock"],
  ["p30","Dermaluxe Demo","Daily Mineral Veil","Skincare","Sunscreen",1099,4.8,590,img("1556229010-2c1c1c9f6f5c"),["Sensitive","Dry","Normal","Combination","Oily"],["Redness","Pigmentation","Uneven Skin Tone"],["Mineral Filters","Ceramides","Vitamin E"],"A demo mineral sunscreen with a soft veil finish.",["Daily UV protection","Comfortable feel","Sensitive-skin focused"],["spf","mineral"],"In stock"]
].map(p => ({id:p[0],brand:p[1],name:p[2],category:p[3],subcategory:p[4],price:p[5],rating:p[6],reviewCount:p[7],image:p[8],skinTypes:p[9],concerns:p[10],ingredients:p[11],ingredientBenefits:p[11].map(x=>"Supports a polished cosmetic routine"),description:p[12],benefits:p[13],tags:p[14],availability:p[15]}));

const INGREDIENTS = {
  "Niacinamide":["A form of vitamin B3 commonly used in cosmetic formulas.","Oil-balancing, barrier-support and tone-focused cosmetic routines.","Oily, Combination, Normal","Oiliness, Pores, Uneven Skin Tone, Dullness"],
  "Hyaluronic Acid":["A humectant commonly used to attract and hold water in cosmetic formulations.","Hydration-focused products and plumping-looking finishes.","Dry, Normal, Combination, Sensitive","Dryness, Fine Lines, Dullness"],
  "Vitamin C":["An antioxidant ingredient widely used in brightening-focused cosmetics.","Glow and even-looking tone routines.","Normal, Dry, Combination, Oily","Dullness, Dark Spots, Pigmentation"],
  "Salicylic Acid":["A beta hydroxy acid commonly used in exfoliating cosmetic products.","Pore and oil-focused routines.","Oily, Combination","Acne, Pores, Oiliness"],
  "Retinol":["A vitamin A derivative used in many cosmetic anti-aging formulas.","Texture and fine-line-focused cosmetic routines.","Normal, Dry, Combination, Oily","Fine Lines, Dullness, Uneven Skin Tone"],
  "Ceramides":["Lipids commonly included in formulas designed to support the skin barrier.","Moisturizing and barrier-focused cosmetics.","Dry, Sensitive, Normal","Dryness, Redness, Fine Lines"],
  "Azelaic Acid":["An ingredient used in cosmetic formulas focused on tone and texture.","Even-looking tone and blemish-focused routines.","Oily, Combination, Sensitive","Pigmentation, Redness, Acne, Uneven Skin Tone"],
  "AHA":["Alpha hydroxy acids used in exfoliating cosmetic formulations.","Smoother-looking and glow-focused routines.","Normal, Oily, Combination","Dullness, Uneven Skin Tone, Pores"],
  "BHA":["Beta hydroxy acids used in exfoliating cosmetic formulations.","Pore and oil-focused routines.","Oily, Combination","Pores, Oiliness, Acne"]
};

const skinTypes=["Normal","Dry","Oily","Combination","Sensitive"];
const concerns=["Acne","Dark Spots","Pigmentation","Dullness","Dryness","Oiliness","Uneven Skin Tone","Fine Lines","Redness","Pores"];
const budgets=[["Under ₹500",500],["₹500–₹1,000",1000],["₹1,000–₹1,500",1500],["₹1,500–₹2,500",2500],["₹2,500+",99999]];
const prefIngredients=Object.keys(INGREDIENTS);
const avoidIngredients=["Fragrance","Essential Oils","Alcohol"];
const beautyPrefs=["Minimal Routine","Complete Routine","Hydration Focus","Brightening Focus","Acne Care Focus","Anti-Aging Focus"];

const load = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const save = (key,val) => localStorage.setItem(key, JSON.stringify(val));

function scoreProduct(p, profile={}) {
  let s=0;
  if(profile.skinType && profile.skinType!=="Not Sure") s += p.skinTypes.includes(profile.skinType)?30:0;
  const cs=profile.concerns||[];
  s += Math.min(25, cs.filter(c=>p.concerns.includes(c)).length*8.34);
  const ips=profile.ingredients||[];
  s += Math.min(20, ips.filter(i=>p.ingredients.includes(i)).length*6.67);
  const maxBudget=profile.budgetMax ?? 2500;
  s += p.price<=maxBudget?10:0;
  const pref=profile.beautyPreference;
  if(pref==="Hydration Focus" && p.ingredients.some(i=>["Hyaluronic Acid","Ceramides"].includes(i))) s+=10;
  else if(pref==="Brightening Focus" && p.ingredients.some(i=>["Vitamin C","AHA","Azelaic Acid"].includes(i))) s+=10;
  else if(pref==="Acne Care Focus" && p.ingredients.some(i=>["Salicylic Acid","BHA","Niacinamide"].includes(i))) s+=10;
  else if(pref==="Anti-Aging Focus" && p.ingredients.some(i=>["Retinol","Peptides"].includes(i))) s+=10;
  else if(pref==="Minimal Routine") s+=p.subcategory==="Serum"?5:0;
  else if(pref==="Complete Routine") s+=p.category==="Skincare"?5:0;
  s += Math.min(5, p.rating);
  return Math.round(Math.min(100,s));
}
function matchReason(p, profile) {
  const reasons=[];
  if(profile.skinType && p.skinTypes.includes(profile.skinType)) reasons.push("Matches your skin type");
  if((profile.concerns||[]).some(c=>p.concerns.includes(c))) reasons.push("Matches a selected concern");
  if((profile.ingredients||[]).some(i=>p.ingredients.includes(i))) reasons.push("Contains a preferred ingredient");
  if(p.price <= (profile.budgetMax??2500)) reasons.push("Fits your budget");
  if(!reasons.length) reasons.push("Strong overall catalogue match");
  return reasons.slice(0,4);
}

function Header({page,setPage,cartCount,wishCount,setMenu}) {
  return <header className="header"><div className="nav wrap">
    <button className="logo" onClick={()=>setPage("home")}><span>Beauty</span>Match<div className="logo-dot">✦</div></button>
    <nav className="desktop-nav">{["home","shop","quiz","compare","routine","ingredients","mybeauty","wishlist"].map(x=><button key={x} className={page===x?"active":""} onClick={()=>setPage(x)}>{x==="mybeauty"?"My Beauty":x==="quiz"?"Skin Quiz":x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
    <div className="nav-actions"><button onClick={()=>setPage("shop")}><Search size={19}/></button><button onClick={()=>setPage("wishlist")} className="badge-btn"><Heart size={19}/>{wishCount>0&&<b>{wishCount}</b>}</button><button onClick={()=>setPage("cart")} className="badge-btn"><ShoppingBag size={19}/>{cartCount>0&&<b>{cartCount}</b>}</button><button className="mobile-only" onClick={()=>setMenu(true)}><Menu/></button></div>
  </div></header>
}
function MobileMenu({setMenu,setPage}) { return <div className="mobile-menu"><button className="close" onClick={()=>setMenu(false)}><X/></button>{["home","shop","quiz","compare","routine","ingredients","mybeauty","wishlist","cart"].map(x=><button key={x} onClick={()=>{setPage(x);setMenu(false)}}>{x==="mybeauty"?"My Beauty":x==="quiz"?"Skin Quiz":x[0].toUpperCase()+x.slice(1)}</button>)}</div> }

function ProductCard({p,score,onOpen,onCart,onWish,wished,onCompare,compared}) {
 return <article className="product-card">
   <div className="product-img" onClick={onOpen}><img src={p.image}/><span className="pill">{p.category}</span><button className={`heart ${wished?"saved":""}`} onClick={e=>{e.stopPropagation();onWish()}}><Heart size={18} fill={wished?"currentColor":"none"}/></button></div>
   <div className="product-body" onClick={onOpen}><div className="brand">{p.brand}</div><h3>{p.name}</h3><div className="rating"><Star size={14} fill="currentColor"/>{p.rating} <span>({p.reviewCount})</span></div><div className="price">₹{p.price.toLocaleString("en-IN")}</div>{score!==undefined&&<div className="match"><span>BeautyMatch</span><strong>{score}%</strong><i><em style={{width:`${score}%`}}/></i></div>}</div>
   <div className="card-actions"><button onClick={onCompare} className={compared?"selected":""}><GitCompare size={16}/> Compare</button><button onClick={onCart}><ShoppingBag size={16}/> Add</button></div>
 </article>
}

function Home({setPage,profile,recs,onOpen}) {
 const trending=PRODUCTS.slice(0,4);
 return <main>
  <section className="hero"><div className="wrap hero-grid"><div><div className="eyebrow"><Sparkles size={16}/> PERSONALIZED BEAUTY DISCOVERY</div><h1>Find Beauty Products That <em>Match</em> Your Skin</h1><p>Discover products based on your skin type, concerns, preferences and budget.</p><div className="hero-buttons"><button className="btn primary" onClick={()=>setPage("quiz")}>Take the Skin Quiz <ChevronRight/></button><button className="btn ghost" onClick={()=>setPage("shop")}>Explore Products</button></div><div className="hero-trust"><span>✦ 30+ demo products</span><span>♡ Personalized matches</span><span>◉ No medical claims</span></div></div><div className="hero-art"><div className="orb orb1"/><div className="orb orb2"/><div className="hero-card"><Sparkles size={28}/><strong>BeautyMatch</strong><span>Your skin. Your preferences. Your match.</span></div><div className="floating f1">✓ 94% Match</div><div className="floating f2">♡ 850 Points</div></div></div></section>
  <section className="section wrap"><div className="section-head"><div><span className="eyebrow">EXPLORE</span><h2>Shop by Skin Type</h2></div><button className="text-btn" onClick={()=>setPage("shop")}>View all <ChevronRight size={16}/></button></div><div className="skin-grid">{skinTypes.map((s,i)=><button key={s} onClick={()=>setPage("shop")}><div className={`skin-circle c${i}`}>{["○","◌","◉","◒","♡"][i]}</div><strong>{s}</strong><span>Explore matches</span></button>)}</div></section>
  <section className="section soft"><div className="wrap"><div className="section-head"><div><span className="eyebrow">CURATED FOR YOU</span><h2>Trending Now</h2></div><button className="text-btn" onClick={()=>setPage("shop")}>Shop all <ChevronRight size={16}/></button></div><div className="product-grid">{trending.map(p=><ProductCard key={p.id} p={p} onOpen={()=>onOpen(p)} onCart={()=>{}} onWish={()=>{}} wished={false} onCompare={()=>{}} compared={false}/>)}</div></div></section>
  <section className="match-banner wrap"><div><span className="eyebrow">YOUR PERSONAL BEAUTY PROFILE</span><h2>Not sure where to start?</h2><p>Take our 60-second quiz and get a personalized product shortlist.</p><button className="btn primary" onClick={()=>setPage("quiz")}>Find My Matches <Sparkles size={17}/></button></div><div className="score-demo"><div><strong>94%</strong><span>BeautyMatch Score</span></div></div></section>
  <section className="section wrap"><div className="ingredient-preview"><div><span className="eyebrow">INGREDIENT LAB</span><h2>Understand what’s inside.</h2><p>Explore common cosmetic ingredients and discover demo products that contain them.</p><button className="btn ghost" onClick={()=>setPage("ingredients")}>Explore Ingredients</button></div><div className="ingredient-bubbles">{["Niacinamide","Hyaluronic Acid","Vitamin C","Ceramides"].map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className="reviews"><div className="wrap"><div className="section-head"><div><span className="eyebrow">SOCIAL PROOF</span><h2>Made for beauty discovery.</h2></div></div><div className="review-grid">{[["“Finally, a beauty site that explains why a product matches me.”","Demo user · Combination skin"],["“The ingredient explorer makes product browsing much easier.”","Demo user · Dry skin"],["“I love seeing the score change when I change my preferences.”","Demo user · Oily skin"]].map(x=><div className="review" key={x[0]}><div className="stars">★★★★★</div><p>{x[0]}</p><small>{x[1]}</small><span className="demo-label">DEMO REVIEW</span></div>)}</div></div></section>
 </main>
}

function Quiz({setPage,setProfile,profile}) {
 const [step,setStep]=useState(1); const [local,setLocal]=useState(profile||{skinType:"",concerns:[],budgetMax:1000,ingredients:[],avoid:[],beautyPreference:""});
 const toggle=(key,v)=>setLocal(x=>({...x,[key]:x[key].includes(v)?x[key].filter(a=>a!==v):[...x[key],v]}));
 const next=()=>{if(step<6)setStep(step+1);else{setProfile(local);setPage("results")}};
 const back=()=>step>1&&setStep(step-1);
 const data=[["Skin Type","Choose your skin type",skinTypes],["Main Concerns","Select everything you want to focus on",concerns],["Budget","What would you like to spend?",budgets.map(x=>x[0])],["Ingredients You Love","Pick ingredients you’re interested in",prefIngredients],["Ingredients to Avoid","Choose ingredients you prefer to avoid",avoidIngredients],["Beauty Preference","What kind of routine feels right?",beautyPrefs]];
 const [title,sub,opts]=data[step-1];
 return <main className="quiz-page"><div className="wrap quiz-wrap"><button className="back-btn" onClick={()=>step===1?setPage("home"):back()}><ArrowLeft size={17}/> Back</button><div className="progress"><span>STEP {step} OF 6</span><div><i style={{width:`${step/6*100}%`}}/></div></div><div className="quiz-box"><div className="quiz-title"><span className="eyebrow">BEAUTYMATCH QUIZ</span><h1>{title}</h1><p>{sub}</p></div><div className="choice-grid">{opts.map(o=>{const val=Array.isArray(o)?o[0]:o;const active=step===1?local.skinType===val:step===2?local.concerns.includes(val):step===3?local.budgetMax===(Array.isArray(o)?o[1]:0):step===4?local.ingredients.includes(val):step===5?local.avoid.includes(val):local.beautyPreference===val;return <button key={val} className={`choice ${active?"chosen":""}`} onClick={()=>step===1?setLocal(x=>({...x,skinType:val})):step===2?toggle("concerns",val):step===3?setLocal(x=>({...x,budgetMax:Array.isArray(o)?o[1]:1000})):step===4?toggle("ingredients",val):step===5?toggle("avoid",val):setLocal(x=>({...x,beautyPreference:val}))}>{active&&<Check size={18}/>}<strong>{val}</strong></button>})}</div><div className="quiz-bottom"><span>{step===2||step===4||step===5?"You can select multiple":""}</span><button className="btn primary" onClick={next}>{step===6?"See My Matches":"Continue"} <ChevronRight/></button></div></div><p className="disclaimer">BeautyMatch is a product discovery demo. Recommendations are for general informational purposes only and are not medical advice.</p></div></main>
}

function Results({profile,onOpen,onCart,onWish,wishlist,onCompare,compare}) {
 const scored=useMemo(()=>PRODUCTS.map(p=>({...p,score:scoreProduct(p,profile)})).sort((a,b)=>b.score-a.score).slice(0,8),[profile]);
 return <main className="section wrap results"><div className="eyebrow">YOUR PERSONALIZED RESULTS</div><h1>Your BeautyMatch Profile</h1><div className="profile-strip"><div><span>Skin Type</span><strong>{profile.skinType||"Not selected"}</strong></div><div><span>Concerns</span><strong>{profile.concerns?.length||0} selected</strong></div><div><span>Budget</span><strong>Up to ₹{profile.budgetMax?.toLocaleString("en-IN")}</strong></div><div><span>Ingredients</span><strong>{profile.ingredients?.length||0} preferred</strong></div></div><div className="section-head result-head"><div><span className="eyebrow">RULE-BASED MATCHING</span><h2>Top Matches For You</h2></div><button className="btn ghost" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>Refine Quiz</button></div><div className="product-grid">{scored.map(p=><ProductCard key={p.id} p={p} score={p.score} onOpen={()=>onOpen(p)} onCart={()=>onCart(p)} onWish={()=>onWish(p.id)} wished={wishlist.includes(p.id)} onCompare={()=>onCompare(p)} compared={compare.some(x=>x.id===p.id)}/>)}</div></main>
}

function Shop({onOpen,onCart,onWish,wishlist,onCompare,compare,profile}) {
 const [q,setQ]=useState(""); const [category,setCategory]=useState("All"); const [sort,setSort]=useState("Best Match"); const [max,setMax]=useState(2500); const [rating,setRating]=useState(0);
 const list=useMemo(()=>{let a=PRODUCTS.filter(p=>(category==="All"||p.category===category)&&p.price<=max&&p.rating>=rating&&(!q||[p.name,p.brand,p.category,p.subcategory,...p.ingredients,...p.skinTypes,...p.concerns].join(" ").toLowerCase().includes(q.toLowerCase()))).map(p=>({...p,score:scoreProduct(p,profile)}));if(sort==="Price Low to High")a.sort((x,y)=>x.price-y.price);else if(sort==="Price High to Low")a.sort((x,y)=>y.price-x.price);else if(sort==="Highest Rated")a.sort((x,y)=>y.rating-x.rating);else a.sort((x,y)=>y.score-x.score);return a},[q,category,sort,max,rating,profile]);
 return <main className="section wrap"><div className="shop-top"><div><span className="eyebrow">THE CATALOGUE</span><h1>Explore Beauty</h1><p>{list.length} demo products matched your filters.</p></div><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, brands, ingredients..."/></div></div><div className="filters"><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option><option>Skincare</option><option>Haircare</option><option>Body Care</option><option>Makeup</option></select><select value={max} onChange={e=>setMax(+e.target.value)}><option value="2500">Any price</option><option value="500">Under ₹500</option><option value="1000">Under ₹1,000</option><option value="1500">Under ₹1,500</option><option value="2000">Under ₹2,000</option></select><select value={rating} onChange={e=>setRating(+e.target.value)}><option value="0">Any rating</option><option value="4.5">4.5+ stars</option><option value="4.7">4.7+ stars</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option>Best Match</option><option>Price Low to High</option><option>Price High to Low</option><option>Highest Rated</option></select><span className="filter-note"><SlidersHorizontal size={16}/> Smart filters</span></div>{list.length?<div className="product-grid">{list.map(p=><ProductCard key={p.id} p={p} score={p.score} onOpen={()=>onOpen(p)} onCart={()=>onCart(p)} onWish={()=>onWish(p.id)} wished={wishlist.includes(p.id)} onCompare={()=>onCompare(p)} compared={compare.some(x=>x.id===p.id)}/>)}</div>:<Empty title="No matches found" text="Try a broader search or reset your filters."/>}</main>
}

function ProductPage({p,profile,onBack,onCart,onWish,wished,onCompare,compared}) {
 const score=scoreProduct(p,profile); const alert=(profile.avoid||[]).some(x=>p.ingredients.includes(x));
 const similar=PRODUCTS.filter(x=>x.id!==p.id&&x.skinTypes.some(s=>p.skinTypes.includes(s))).slice(0,3);
 return <main className="section wrap product-page"><button className="back-btn" onClick={onBack}><ArrowLeft size={17}/> Back to shopping</button><div className="product-detail"><div className="detail-img"><img src={p.image}/><span>DEMO PRODUCT</span></div><div className="detail-info"><div className="brand">{p.brand}</div><h1>{p.name}</h1><div className="rating big"><Star size={17} fill="currentColor"/>{p.rating} <span>{p.reviewCount} demo reviews</span></div><div className="detail-price">₹{p.price.toLocaleString("en-IN")}</div><p>{p.description}</p><div className="score-box"><div><strong>{score}%</strong><span>BeautyMatch Score</span></div><div><b>Why this matches you</b>{matchReason(p,profile).map(x=><small key={x}><Check size={14}/>{x}</small>)}</div></div>{alert&&<div className="alert"><Bell/><div><strong>Ingredient Alert</strong><p>This product contains an ingredient in your avoid list.</p></div></div>}<div className="tag-row">{p.skinTypes.map(x=><span key={x}>{x} skin</span>)}</div><div className="detail-buttons"><button className={`btn ${wished?"saved-btn":"ghost"}`} onClick={onWish}><Heart size={17} fill={wished?"currentColor":"none"}/> {wished?"Saved":"Wishlist"}</button><button className={`btn ${compared?"saved-btn":"ghost"}`} onClick={onCompare}><GitCompare size={17}/> {compared?"Compared":"Compare"}</button><button className="btn primary" onClick={()=>onCart(p)}><ShoppingBag size={17}/> Add to Cart</button></div></div></div><div className="detail-sections"><div><h2>Key Benefits</h2><ul>{p.benefits.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></div><div><h2>Ingredients</h2><div className="ingredient-list">{p.ingredients.map(x=><span key={x}>{x}</span>)}</div></div><div><h2>Popular With Similar Profiles</h2><div className="mini-grid">{similar.map(x=><div className="mini" key={x.id}><img src={x.image}/><div><strong>{x.name}</strong><small>{x.brand}</small><b>₹{x.price}</b></div></div>)}</div></div></div></main>
}

function Ingredients({onOpen}) {const [q,setQ]=useState("");const names=Object.keys(INGREDIENTS).filter(x=>x.toLowerCase().includes(q.toLowerCase()));return <main className="section wrap"><div className="center-head"><span className="eyebrow">INGREDIENT LAB</span><h1>Know what’s inside.</h1><p>Explore common cosmetic ingredients in simple, demo-friendly language.</p><div className="searchbox ingredient-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search an ingredient..."/></div></div><div className="ingredient-grid">{names.map(n=>{const d=INGREDIENTS[n];const products=PRODUCTS.filter(p=>p.ingredients.includes(n)).slice(0,3);return <article className="ingredient-card" key={n}><div className="ingredient-icon">✦</div><h2>{n}</h2><p>{d[0]}</p><div className="ing-row"><span>Common uses</span><strong>{d[1]}</strong></div><div className="ing-row"><span>Often explored by</span><strong>{d[2]}</strong></div><div className="ing-tags">{d[3].split(", ").map(x=><span key={x}>{x}</span>)}</div><div className="ing-products"><b>Products containing it</b>{products.map(p=><button key={p.id} onClick={()=>onOpen(p)}>{p.name}<ChevronRight size={14}/></button>)}</div></article>})}</div></main>}

function Compare({items,onRemove,onOpen}) {return <main className="section wrap"><div className="section-head"><div><span className="eyebrow">DECISION TOOL</span><h1>Compare Products</h1><p>Compare up to three demo products side by side.</p></div></div>{!items.length?<Empty title="Your comparison is empty" text="Add products from the shop using the Compare button."/>:<div className="compare-table"><table><thead><tr><th>Attribute</th>{items.map(p=><th key={p.id}><button onClick={()=>onRemove(p.id)}><X/></button><img src={p.image}/><strong onClick={()=>onOpen(p)}>{p.name}</strong><small>{p.brand}</small></th>)}</tr></thead><tbody>{[["Price",p=>`₹${p.price}`],["Rating",p=>`★ ${p.rating}`],["BeautyMatch Score",p=>`${scoreProduct(p,load("beautyProfile",{}))}%`],["Skin Types",p=>p.skinTypes.join(", ")],["Concerns",p=>p.concerns.length?p.concerns.join(", "):"—"],["Key Ingredients",p=>p.ingredients.join(", ")]].map(([k,f])=><tr key={k}><td>{k}</td>{items.map(p=><td key={p.id}>{f(p)}</td>)}</tr>)}</tbody></table></div>}</main>}

function Routine({profile,onCart}) {const [budget,setBudget]=useState(1500);const pool=PRODUCTS.map(p=>({...p,score:scoreProduct(p,profile)})).sort((a,b)=>b.score-a.score);const slots=[["Cleanser",p=>p.subcategory==="Cleanser"],["Serum",p=>p.subcategory==="Serum"],["Moisturizer",p=>p.subcategory==="Moisturizer"],["Sunscreen",p=>p.subcategory==="Sunscreen"]];let chosen=[];let total=0;for(const [slot,fn] of slots){const p=pool.find(x=>fn(x)&&!chosen.some(c=>c.id===x.id)&&total+x.price<=budget);if(p){chosen.push({...p,slot});total+=p.price;}}const match=chosen.length?Math.round(chosen.reduce((a,p)=>a+p.score,0)/chosen.length):0;return <main className="section wrap"><div className="routine-hero"><div><span className="eyebrow">BUILD MY ROUTINE</span><h1>A routine that fits <em>you.</em></h1><p>Build a demo morning routine using your BeautyMatch profile and a maximum budget.</p></div><div className="budget-control"><label>Maximum budget <strong>₹{budget.toLocaleString("en-IN")}</strong></label><input type="range" min="500" max="3000" step="100" value={budget} onChange={e=>setBudget(+e.target.value)}/></div></div><div className="routine-stats"><div><strong>₹{total.toLocaleString("en-IN")}</strong><span>Routine Total</span></div><div><strong>₹{Math.max(0,budget-total).toLocaleString("en-IN")}</strong><span>Amount Remaining</span></div><div><strong>{match}%</strong><span>Overall Match</span></div><div><strong>{chosen.length}</strong><span>Products</span></div></div><div className="routine-list"><h2>Morning Routine</h2>{chosen.map(p=><div className="routine-item" key={p.id}><img src={p.image}/><div><span>{p.slot}</span><strong>{p.name}</strong><small>{p.brand} · {p.score}% match</small></div><b>₹{p.price}</b><button onClick={()=>onCart(p)}>Add</button></div>)}</div><p className="disclaimer">Demo routine only. Cosmetic recommendations are for general product discovery and are not medical advice.</p></main>}

function Wishlist({items,onOpen,onCart,onWish}) {const list=PRODUCTS.filter(p=>items.includes(p.id));return <main className="section wrap"><span className="eyebrow">SAVED FOR LATER</span><h1>My Wishlist</h1><p>Keep your favorite demo products in one place.</p>{list.length?<div className="product-grid">{list.map(p=><ProductCard key={p.id} p={p} onOpen={()=>onOpen(p)} onCart={()=>onCart(p)} onWish={()=>onWish(p.id)} wished onCompare={()=>{}} compared={false}/>)}</div>:<Empty title="Your wishlist is waiting" text="Tap the heart on a product to save it here."/>}</main>}

function Cart({cart,onQty,onRemove,onCheckout,onCart}) {const subtotal=cart.reduce((a,x)=>a+x.price*x.qty,0);return <main className="section wrap cart-page"><span className="eyebrow">YOUR BAG</span><h1>Shopping Cart</h1>{!cart.length?<Empty title="Your bag is empty" text="Discover your next BeautyMatch and add it here."/>:<div className="cart-grid"><div>{cart.map(x=><div className="cart-item" key={x.id}><img src={x.image}/><div><span>{x.brand}</span><h3>{x.name}</h3><b>₹{x.price.toLocaleString("en-IN")}</b><div className="qty"><button onClick={()=>onQty(x.id,-1)}><Minus size={14}/></button><strong>{x.qty}</strong><button onClick={()=>onQty(x.id,1)}><Plus size={14}/></button></div></div><button className="remove" onClick={()=>onRemove(x.id)}><Trash2 size={18}/></button></div>)}<div className="complete-routine"><Sparkles/><div><strong>Complete Your Routine</strong><p>Add a complementary product from our catalogue.</p></div><button className="btn ghost" onClick={()=>onCart(PRODUCTS.find(p=>p.subcategory==="Sunscreen"))}>Add SPF</button></div></div><aside className="summary"><h2>Order Summary</h2><div><span>Subtotal</span><b>₹{subtotal.toLocaleString("en-IN")}</b></div><div><span>Demo discount</span><b>− ₹{Math.min(150,Math.round(subtotal*.05)).toLocaleString("en-IN")}</b></div><hr/><div className="total"><span>Total</span><strong>₹{(subtotal-Math.min(150,Math.round(subtotal*.05))).toLocaleString("en-IN")}</strong></div><button className="btn primary wide" onClick={onCheckout}>Checkout <ChevronRight/></button><small>Demo checkout only. No real payment is processed.</small></aside></div>}</main>}

function Checkout({cart,setPage}) {const [done,setDone]=useState(false);const [form,setForm]=useState({name:"",email:"",phone:"",address:"",city:"",postal:"",payment:"UPI"});const update=k=>e=>setForm({...form,[k]:e.target.value});if(done)return <main className="section wrap success"><div className="success-icon"><Check/></div><span className="eyebrow">DEMO ORDER</span><h1>Order Confirmed</h1><p>Your demo order has been created successfully.</p><div className="order-no">Order #BM-{Math.floor(100000+Math.random()*899999)}</div><button className="btn primary" onClick={()=>setPage("home")}>Continue Shopping</button></main>;return <main className="section wrap checkout"><div><span className="eyebrow">DEMO CHECKOUT</span><h1>Complete your order</h1><p>Nothing is charged. This is a front-end portfolio demo.</p><div className="form-grid">{["name","email","phone","address","city","postal"].map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)}<input value={form[k]} onChange={update(k)} placeholder={`Enter ${k}`}/></label>)}</div><h2>Payment Method</h2><div className="payment-options">{["UPI","Card","Cash on Delivery"].map(x=><button key={x} className={form.payment===x?"chosen":""} onClick={()=>setForm({...form,payment:x})}><ShieldCheck size={17}/>{x}</button>)}</div><button className="btn primary wide" onClick={()=>setDone(true)}>Place Demo Order</button></div><aside className="summary"><h2>Your Bag</h2>{cart.map(x=><div className="summary-product" key={x.id}><img src={x.image}/><span>{x.name} × {x.qty}</span><b>₹{x.price*x.qty}</b></div>)}</aside></main>}

function MyBeauty({profile,wishlist,routinePoints,setPage}) {return <main className="section wrap"><div className="profile-hero"><div className="avatar">BM</div><div><span className="eyebrow">MY BEAUTY</span><h1>Your Beauty Profile</h1><p>Your demo personalization hub.</p></div><button className="btn ghost" onClick={()=>setPage("quiz")}>Edit Profile</button></div><div className="dashboard-grid"><div className="dash-card score-dash"><span>BeautyMatch Score</span><strong>94%</strong><small>Profile completeness</small><div className="progress-line"><i style={{width:"94%"}}/></div><div className="dash-card"><Award/><span>BeautyPoints</span><strong>{routinePoints}</strong><small>Earn more by completing demo actions</small></div><div className="dash-card"><RotateCcw/><span>Routine Streak</span><strong>7 days</strong><small>Demo tracker</small></div><div className="dash-card"><Heart/><span>Wishlist</span><strong>{wishlist.length}</strong><small>Saved products</small></div></div><div className="profile-details"><div><h2>Beauty Profile</h2><p><b>Skin Type:</b> {profile.skinType||"Not set"}</p><p><b>Concerns:</b> {(profile.concerns||[]).join(", ")||"None selected"}</p><p><b>Budget:</b> Up to ₹{(profile.budgetMax||1000).toLocaleString("en-IN")}</p></div><div><h2>Preferences</h2><p><b>Preferred:</b> {(profile.ingredients||[]).join(", ")||"None selected"}</p><p><b>Avoid:</b> {(profile.avoid||[]).join(", ")||"None selected"}</p><p><b>Routine:</b> {profile.beautyPreference||"Not set"}</p></div></div></main>}

function Assistant({profile,onCart,setPage}) {const [open,setOpen]=useState(false);const [q,setQ]=useState("");const [messages,setMessages]=useState([{from:"bot",text:"Hi! I’m Ask BeautyMatch. Tell me your skin type, concern or budget and I’ll suggest demo products."}]);const send=()=>{if(!q.trim())return;const text=q;setMessages(m=>[...m,{from:"user",text},{from:"bot",text:answer(text,profile)}]);setQ("")};return <><button className="assistant-fab" onClick={()=>setOpen(!open)}>{open?<X/>:<MessageCircle/>}</button>{open&&<div className="assistant"><div className="assistant-head"><div><strong>Ask BeautyMatch</strong><small>Demo product discovery assistant</small></div><Sparkles/></div><div className="messages">{messages.map((m,i)=><div className={`msg ${m.from}`} key={i}>{m.text}</div>)}</div><div className="assistant-input"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="e.g. oily skin, ₹1500"/><button onClick={send}><Send size={17}/></button></div><small className="assistant-note">General product discovery only — not medical advice.</small></div>}</>}
function answer(text,profile){const low=text.toLowerCase();let p=profile||{};if(low.includes("oily"))p={...p,skinType:"Oily"};if(low.includes("dry"))p={...p,skinType:"Dry"};const m=low.match(/₹\s?(\d[\d,]*)/);if(m)p={...p,budgetMax:+m[1].replace(/,/g,"")};if(low.includes("acne"))p={...p,concerns:[...(p.concerns||[]),"Acne"]};const a=PRODUCTS.map(x=>({...x,s:scoreProduct(x,p)})).sort((x,y)=>y.s-x.s).slice(0,3);return `Based on the demo profile, I’d explore ${a.map(x=>x.name).join(", ")}. Their match scores are ${a.map(x=>scoreProduct(x,p)+"%").join(", ")}. Open a product to see the reasons behind the match.`}

function Empty({title,text}) {return <div className="empty"><div>✦</div><h2>{title}</h2><p>{text}</p></div>}

function App(){
 const [page,setPage]=useState("home");const [menu,setMenu]=useState(false);const [profile,setProfile]=useState(load("beautyProfile",{skinType:"",concerns:[],budgetMax:1000,ingredients:[],avoid:[],beautyPreference:""}));const [wishlist,setWishlist]=useState(load("wishlist",[]));const [cart,setCart]=useState(load("cart",[]));const [compare,setCompare]=useState([]);const [product,setProduct]=useState(null);const [points,setPoints]=useState(load("points",850));const [toast,setToast]=useState("");
 useEffect(()=>save("beautyProfile",profile),[profile]);useEffect(()=>save("wishlist",wishlist),[wishlist]);useEffect(()=>save("cart",cart),[cart]);useEffect(()=>save("points",points),[points]);
 const notify=t=>{setToast(t);setTimeout(()=>setToast(""),2200)};
 const openProduct=p=>{setProduct(p);setPage("product");window.scrollTo(0,0)};
 const addCart=p=>{if(!p)return;setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]);setPoints(x=>x+5);notify("Added to your bag")};
 const wish=id=>{setWishlist(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);setPoints(x=>x+2);notify(wishlist.includes(id)?"Removed from wishlist":"Saved to wishlist")};
 const qty=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(1,x.qty+d)}));
 const remove=id=>setCart(c=>c.filter(x=>x.id!==id));
 const comp=p=>{setCompare(c=>c.some(x=>x.id===p.id)?c.filter(x=>x.id!==p.id):c.length<3?[...c,p]:c);notify(compare.length>=3&&!compare.some(x=>x.id===p.id)?"Comparison limit is 3":"Comparison updated")};
 const common={onOpen:openProduct,onCart:addCart,onWish:wish,wishlist,onCompare:comp,compare};
 let content;
 if(page==="home")content=<Home setPage={setPage} profile={profile} recs={PRODUCTS.slice(0,4)} onOpen={openProduct}/>;
 else if(page==="shop")content=<Shop {...common} profile={profile}/>;
 else if(page==="quiz")content=<Quiz setPage={setPage} setProfile={p=>{setProfile(p);setPoints(x=>x+25)}} profile={profile}/>;
 else if(page==="results")content=<Results profile={profile} {...common}/>;
 else if(page==="product"&&product)content=<ProductPage p={product} profile={profile} onBack={()=>setPage("shop")} onCart={()=>addCart(product)} onWish={()=>wish(product.id)} wished={wishlist.includes(product.id)} onCompare={()=>comp(product)} compared={compare.some(x=>x.id===product.id)}/>;
 else if(page==="ingredients")content=<Ingredients onOpen={openProduct}/>;
 else if(page==="compare")content=<Compare items={compare} onRemove={id=>setCompare(c=>c.filter(x=>x.id!==id))} onOpen={openProduct}/>;
 else if(page==="routine")content=<Routine profile={profile} onCart={addCart}/>;
 else if(page==="wishlist")content=<Wishlist items={wishlist} {...common}/>;
 else if(page==="cart")content=<Cart cart={cart} onQty={qty} onRemove={remove} onCheckout={()=>setPage("checkout")} onCart={addCart}/>;
 else if(page==="checkout")content=<Checkout cart={cart} setPage={setPage}/>;
 else if(page==="mybeauty")content=<MyBeauty profile={profile} wishlist={wishlist} routinePoints={points} setPage={setPage}/>;
 else content=<Home setPage={setPage} profile={profile} recs={PRODUCTS.slice(0,4)} onOpen={openProduct}/>;
 return <><Header page={page} setPage={setPage} cartCount={cart.reduce((a,x)=>a+x.qty,0)} wishCount={wishlist.length} setMenu={setMenu}/>{menu&&<MobileMenu setMenu={setMenu} setPage={setPage}/>} {content}<Assistant profile={profile}/>{toast&&<div className="toast"><Check size={17}/>{toast}</div>}<Footer setPage={setPage}/></>
}
function Footer({setPage}){return <footer><div className="wrap footer-grid"><div><button className="logo"><span>Beauty</span>Match</button><p>Find What Matches Your Skin.</p><small>Personalized beauty discovery for a portfolio demo.</small></div><div><strong>Explore</strong><button onClick={()=>setPage("shop")}>Shop</button><button onClick={()=>setPage("quiz")}>Skin Quiz</button><button onClick={()=>setPage("ingredients")}>Ingredient Lab</button></div><div><strong>My Beauty</strong><button onClick={()=>setPage("routine")}>My Routine</button><button onClick={()=>setPage("wishlist")}>Wishlist</button><button onClick={()=>setPage("mybeauty")}>Beauty Profile</button></div><div><strong>Demo</strong><button onClick={()=>setPage("compare")}>Compare</button><button onClick={()=>setPage("cart")}>Cart</button><button onClick={()=>setPage("home")}>Home</button></div></div><div className="wrap footer-bottom">© 2026 BeautyMatch Demo · Product data and reviews are fictional/demo content. · <span>Recommendations are general informational content, not medical advice.</span></div></footer>}
createRoot(document.getElementById("root")).render(<App/>);
